name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^2.0.4
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^6.5.9
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
